source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'SwiftWorkFrame' do
    pod 'Alamofire', '~> 4.4’
    pod 'ObjectMapper'
    pod 'ESPullToRefresh'
    pod 'Kingfisher'
end
